### ISSUE TITLE
Allow to set resolution level for retrieving planes of pyramidal images

### ISSUE THREAD

**Issue by dominikl** [ome/omero-gateway-java#48]
At the moment you can't get pixel data at specific zoom levels from pyramidal images. An example like [OMERO.py: How to get tiles at different zoom level (pyramidal image)?](https://forum.image.sc/t/omero-py-how-to-get-tiles-at-different-zoom-level-pyramidal-image/45643) is afaik not possible using the Java gateway. 
At a first glance this could be quite tricky, if it needs the whole rendering stack from Insight, but maybe there's an alternative way.

**Comment by will-moore** [comment]
`rawPixelsStore.setResolutionLevel()` is not just Python:
https://downloads.openmicroscopy.org/omero/5.4.10/api/ome/api/RawPixelsStore.html#setResolutionLevel-int-
