### ISSUE TITLE
Bump bioformats to latest version

### ISSUE THREAD

**Issue by dominikl** [ome/omero-gateway-java#65]
Bioformats needs to be bumped to the latest version. Would be nice to have the ZarrReader included. But I can't find out where the Bioformats dependency actually comes from, ie. where exactly to bump the version.
/cc @jburel

**Comment by jburel** [comment]
ZarrReader is not included in BioFormats 
Gateway 5.6.10 already included the latest Bio-Formats
BF happens here https://github.com/ome/omero-model/blob/master/build.gradle#L34
then a series of release needs to happen
