### ISSUE TITLE
OMERO.table much bigger than csv

### ISSUE THREAD

**Issue by dominikl** [ome/omero-gateway-java#75]
If you create an OMERO.table from a csv it's much bigger than the csv itself. If you use Python (I used the "Populate Metadata" script) the size is bigger too, but not quite as big.

Example code:
```
        try (Gateway gw = new Gateway(new SimpleLogger())) {
            ExperimenterData exp =  gw.connect(lc);
            SecurityContext ctx = new SecurityContext(exp.getGroupId());

            LoadFacility lf = gw.getFacility(LoadFacility.class);
            TablesFacility tf = gw.getFacility(TablesFacility.class);

            TableDataColumn[] columns = new TableDataColumn[3];
            columns[0] =  new TableDataColumn("Image", 0, ImageData.class);
            columns[1] =  new TableDataColumn("Name", 1, String.class);
            columns[2] =  new TableDataColumn("Value", 2, Double.class);

            Object[][] data = new Object[3][5];
            data[0] = new ImageData[] {getImage(238309),
                    getImage(238310l),
                    getImage(238311l),
                    getImage(224666l),
                    getImage(256365l)};
            data[1] = new String[] {"one", "two", "three", "four", "five"};
            data[2] = new Double[] {1d, 2d, 3d, 4d, 5d};

            TableData tableData = new TableData(columns, data);
            DatasetData ds = lf.getDataset(ctx, 8615l);
            tableData = tf.addTable(ctx, ds, "My Data", tableData);
        }
```

The data exported as CSV file is 102 bytes. The Java code creates an OMERO.table with 234kb. The "Populate Metadata" script creates an OMERO.table with 74kb (incl an extra "Image Name" column the scripts adds).
![Screenshot 2023-06-07 at 11 01 20](https://github.com/ome/omero-gateway-java/assets/6575139/d6bb3af9-bcf6-49ba-a5f4-baf2ac49f10c)

But it looks like the "Populate Metadata" script stores everything as String:
![Screenshot 2023-06-07 at 10 59 53](https://github.com/ome/omero-gateway-java/assets/6575139/5ab72e3f-afcc-45bc-ad44-b496ae805022)
![Screenshot 2023-06-07 at 11 00 12](https://github.com/ome/omero-gateway-java/assets/6575139/530c9d4f-4119-45ea-a286-765302db2dd4)

Whereas the Java gateway seems to do the right thing:
![Screenshot 2023-06-07 at 10 59 35](https://github.com/ome/omero-gateway-java/assets/6575139/64d69d2a-3a4c-43a8-b25e-3bcdd757c0e6)
![Screenshot 2023-06-07 at 11 00 03](https://github.com/ome/omero-gateway-java/assets/6575139/bbe4fe20-4754-49d7-b2ca-f0b3f084aed0)

I have to test with a bigger example. With this small example the HDF5 overhead vs CSV is just too massive. But there is a difference between "populate metadata" and the Java gateway methods.

**Comment by ppouchin** [comment]
Using a macro with our batch plugin in Fiji, I generated a table with many "double" columns, the image label, the ROI ID and the image ID. 
It weighed ~1 MB.

I downloaded the table as a CSV (~7 KB) and added the headers to define the column types and removed the image ID column (as there was a problem with an index somehow), but kept the "Label" column and renamed it to "Image Name". I also added a "Dataset Name" column.
Then, I re-uploaded the modified CSV and used the "Populate Metadata" script to generate a new table.
The result was a lighter table (~70 KB).

If I download the tables and open them using HDF5View, the types I observe are these for the initial table:
![image](https://github.com/ome/omero-gateway-java/assets/5746620/189b314d-0bce-4a60-b4c9-124cb625dc3e)
and these for the recreated table:
![image](https://github.com/ome/omero-gateway-java/assets/5746620/bf07bed4-cc1f-4a22-b464-5505b8304165)
which matches the header I provided:
`# header s,roi,s,d,d,d,d,d,d,d,d,d,d,d,d`

I don't see what makes the original table so much heavier, the content is almost identical.

**Comment by dominikl** [comment]
Interesting find, thanks. I wonder why it's different for the Java vs Python API way to create the table. Btw, I tested it with an example from IDR, same here, Java creates such a massive table ("Test") compared to Python API ("bulk_annotations"):
![Screenshot 2023-06-08 at 10 12 59](https://github.com/ome/omero-gateway-java/assets/6575139/4f336737-c8e7-4729-bf8c-7171d53aac38)
And opening the large table with a hex editor shows that it mostly consists of zeros (hence the zipped example on the image.sc post is actually quite small).

**Comment by ppouchin** [comment]
Ok. Out of curiosity, I tried to look where the [table is pushed on OMERO in the Java Gateway](https://github.com/ome/omero-gateway-java/blob/master/src/main/java/omero/gateway/facility/TablesFacility.java#L116), but I see it is done outside the Java API, using the same methods as the Python API.
Could the difference reside in the way the columns are created?

**Comment by ppouchin** [comment]
I see that for String columns, the default size is [SHORT.MAX_VALUE](https://github.com/ome/omero-gateway-java/blob/master/src/main/java/omero/gateway/facility/TablesFacilityHelper.java#L522), could it be related?

**Comment by dominikl** [comment]
Thanks for your help @ppouchin 👍 
I should have spotted that earlier. Hope there aren't many unnceccessarly huge OMERO tables out there.
