### ISSUE TITLE
getMiddleName() throws exception instead of empty string

### ISSUE THREAD

**Issue by Rdornier** [ome/omero-gateway-java#83]
Is there any reasons that [this method](https://github.com/ome/omero-gateway-java/blob/master/src/main/java/omero/gateway/model/ExperimenterData.java#L269) throws an exception ?

```java
    public String getMiddleName() {
        omero.RString n = asExperimenter().getMiddleName();
        if (n == null || n.getValue() == null) {
            throw new IllegalStateException(
                    "The name should never have been null");
        }
        return n.getValue();
    }
```

I think it could simply be written like this (same way as ``getLastName()``
```java
    public String getMiddleName() {
        omero.RString n = asExperimenter().getMiddleName();
        if (n == null || n.getValue() == null) return "";
        return n.getValue();
    }
```

In the same way, is there any reasons to return ``null`` for ``getEmail()``, ``getInstitutiom()``... methods instead of returning an empty string ?

Thanks,
Rémy.

**Comment by dominikl** [comment]
Thanks @Rdornier . Indeed, looks a bit inconsistant to me. I'm not sure, was there any reasoning behind it, why some methods throw an exception, while others return null, and yet others return an emtpy String, @jburel ?
